import { NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';
export class TourApplyModel{
  id:number
  empName:string
  tourID:number
  reqFrom:string
  reqTo:string
  userID:number
  remarks:string
  cOmpanyID:number
  msg:string
  pOptions:number
  department:string
  designation:string
  gradeValue:number
  grandtype:number
  status:number
  empCode:string
  lsDate:any
  lsDateNgb:NgbDateStruct
  leDate:any
  leDateNgb:NgbDateStruct
  laDate:any
  laDateNgb:NgbDateStruct
  accepteDuration:number
  unAccepteDuration:number
  referanceEmpcode:string
  appType:string
  yYYYMMDD:string
  yYYYMMDDNgb:NgbDateStruct
  applyTo:string
  reason:string
  companyID:number
  emgContructNo:string
  emgAddress:string
}
