export class LeaveApply{
    id : number;
    empCode : string;
    lsDate : any;
    leDate : any;
    laDate : any;
    accepteDuration : number;
    lTypedID : number;
    unAccepteDuration : number;
    referanceEmpcode : string;
    withpay : number;
    grandtype : string;
    appType : string;
    yyyymmdd : string;
    aprovedate : string;
    companyID : number;
    applyTo : string;
    recommendTo : string;
    haEmpcode : string;
    haApprove : number;
    reason : string;
    authorityEmpcode : string;
    authorityApprove : number;
    emgContructNo : string;
    emgAddress : string;
    hrApproveID : number;
    userName : string;
    empName:string;
    designation:string;
    department:string;
    leaveTypeName:string;
    typeName:string;
    forwardEmpCode:string;
}
